name: farm_aware
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - images/ 
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
    - family: Itim
      fonts:
        - asset: assets/fonts/Itim-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/static/Inter-Regular.ttf
        - asset: assets/fonts/Inter-VariableFont_slnt,wght.ttf
        - asset: assets/fonts/static/Inter-Light.ttf
        - asset: assets/fonts/static/Inter-Bold.ttf

 
